### ISSUE TITLE
ValueError: num_outputs should be int or long, got 9.

### ISSUE THREAD

**Issue by horacioHao** [andyweizhao/NLP-Capsule#10]
Need for help:

Win10
Python 2.7
tensorflow-gpu 1.10.0
The error is as below by runing 'python ./main.py --model_type CNN --learning_rate 0.0005':

Using TensorFlow backend.
{
  "loss_type": "margin_loss",
  "has_dev": 1,
  "use_orphan": true,
  "learning_rate": 0.0005,
  "batch_size": 25,
  "has_test": 1,
  "num_epochs": 20,
  "model_type": "CNN",
  "margin": 0.2,
  "dataset": "reuters_multilabel_dataset",
  "embedding_type": "static",
  "use_leaky": true
}
loading data...
reuters_multilabel_dataset
Keys: [u'test', u'test_label', u'train', u'train_label', u'w2v']
max sent:  300
vocab size:  21055
vec size:  300
num_classes:  9
Traceback (most recent call last):
  File "./main.py", line 167, in <module>
    poses, activations = baseline_model_cnn(X_embedding, args.num_classes)
  File "D:\PycharmProjects\pythonProject\capsule_text_classification-master\network.py", line 18, in baseline_model_cnn
    activations = tf.sigmoid(slim.fully_connected(nets, num_classes, scope='final_layer', activation_fn=None))
  File "D:\Anaconda\envs\py27\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "D:\Anaconda\envs\py27\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1822, in fully_connected
    (num_outputs,))
ValueError: num_outputs should be int or long, got 9.

**Comment by horacioHao** [comment]
> Need for help:
> 
> Win10
> Python 2.7
> tensorflow-gpu 1.10.0
> The error is as below by runing 'python ./main.py --model_type CNN --learning_rate 0.0005':
> 
> Using TensorFlow backend.
> {
> "loss_type": "margin_loss",
> "has_dev": 1,
> "use_orphan": true,
> "learning_rate": 0.0005,
> "batch_size": 25,
> "has_test": 1,
> "num_epochs": 20,
> "model_type": "CNN",
> "margin": 0.2,
> "dataset": "reuters_multilabel_dataset",
> "embedding_type": "static",
> "use_leaky": true
> }
> loading data...
> reuters_multilabel_dataset
> Keys: [u'test', u'test_label', u'train', u'train_label', u'w2v']
> max sent: 300
> vocab size: 21055
> vec size: 300
> num_classes: 9
> Traceback (most recent call last):
> File "./main.py", line 167, in
> poses, activations = baseline_model_cnn(X_embedding, args.num_classes)
> File "D:\PycharmProjects\pythonProject\capsule_text_classification-master\network.py", line 18, in baseline_model_cnn
> activations = tf.sigmoid(slim.fully_connected(nets, num_classes, scope='final_layer', activation_fn=None))
> File "D:\Anaconda\envs\py27\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
> return func(*args, **current_args)
> File "D:\Anaconda\envs\py27\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1822, in fully_connected
> (num_outputs,))
> ValueError: num_outputs should be int or long, got 9.
