### ISSUE TITLE
RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by luisfredgs** [andyweizhao/NLP-Capsule#2]
Hello, I've tried replicating your experiments, but I got the follow error:

Traceback (most recent call last):
  File "EUR_Cap.py", line 116, in <module>
    poses, activations = capsule_net(data, batch_labels)
  File "/home/jaoa/anaconda3/envs/pyenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jaoa/anaconda3/envs/pyenv/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/jaoa/anaconda3/envs/pyenv/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/jaoa/anaconda3/envs/pyenv/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/jaoa/anaconda3/envs/pyenv/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/jaoa/anaconda3/envs/pyenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jaoa/NLP-Capsule/network.py", line 42, in forward
    nets = self.convs_doc[i](data)
  File "/home/jaoa/anaconda3/envs/pyenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jaoa/anaconda3/envs/pyenv/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 196, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same

My current environment: Python 3.6 and Pytorch 1.1

**Comment by luisfredgs** [comment]
It's solved now :-)
